# MySQL.  Versions 5.0+ are recommended.

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  socket: /tmp/mysql.sock
  database: folio_development

test:
  <<: *default
  database: folio_test

production:
  <<: *default
  database: folio_production
