# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fc62e6b04aeecbff8a5f9487d2bce34ec61496260905ed843dc0a1c1d10d865be147003106caaca166f1816338574b39ebbf8ccf6a990f585240f41aa26c0a4

test:
  secret_key_base: 867b9d7a677c383f0efeab9313a725f7de8d8a7bcc0336281e14df5d096b3e30dacc1f3d5d26cb11d668bf90c589a099774622b8ced7b2a59011deccbc97de57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: fbf638af2cdc8ec8994fc4592c39ce6b7b1dcb9455dcc0c692fca3a636077314e43af8375ca8b63ace2fbed9cdbc5b67fb100d57c9e832f9010353fefbb197e0
  aws_access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>

